apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplejava-deployment
spec:
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      name: sample
      labels:
        app: sample
    spec:
      containers:
        - name: sample
          image: pinturavi/sample-java:latest
          volumeMounts:
            - mountPath: /opt/data
              name: vol
      volumes:
        - name: vol
          hostPath:
            path: /opt/data



